pipeline {
    agent any
    
	stages {
        stage('Build') {
            steps {
                echo 'Building..'
                sh 'mvn -f vote/pom.xml clean install -Dmaven.test.skip=true'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
                sh 'sudo /opt/tomcat/controller/shutdown.sh autopartage'
                sh 'sudo scp /home/cronos/.m2/repository/com/cronos/vote/0.0.1-SNAPSHOT/vote-0.0.1-SNAPSHOT.war autopartage.cronos.lu:/opt/autopartage/webapps autopartage'
                sh 'sudo /opt/tomcat/controller/startup.sh autopartage'
            }
        }
    }
}