pipeline {
    agent any
    
    tools {
    	maven 'mvn-3.6.0'
  	}
    
	stages {
        stage('Build') {
            steps {
                echo 'Building..'
                sh 'mvn build'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
                sh 'mvn test'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}